admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# sonata_block:
# blocks:
#     # enable the SonataAdminBundle block
#     sonata.admin.block.admin_list:
#         contexts: [admin]
